// ICSDK2 - ic_action2.h - standard + other actions
// (this file is automatically generated, do not edit

extern const RAW_ACTION action_001; // Tail wag 1
extern const RAW_ACTION action_002; // Crouch
extern const RAW_ACTION action_003; // Sniffing ground1
extern const RAW_ACTION action_004; // Guard 1
extern const RAW_ACTION action_005; // Dig it
extern const RAW_ACTION action_006; // Sniffing air
extern const RAW_ACTION action_007; // Sitting, flea scratch 1
extern const RAW_ACTION action_008; // Pee right 1
extern const RAW_ACTION action_009; // Pee right 2
extern const RAW_ACTION action_010; // Pee left 1
extern const RAW_ACTION action_011; // Pee left 2
extern const RAW_ACTION action_012; // Sniffing ground 2
extern const RAW_ACTION action_013; // Sniffing ground 3
extern const RAW_ACTION action_014; // Guard 2
extern const RAW_ACTION action_015; // Sniffing and raising hand
extern const RAW_ACTION action_016; // Sit 1
extern const RAW_ACTION action_017; // Play
extern const RAW_ACTION action_018; // Standing neutral 1
extern const RAW_ACTION action_019; // Stretch yawn
extern const RAW_ACTION action_020; // Rocking 1
extern const RAW_ACTION action_021; // Rocking 2
extern const RAW_ACTION action_022; // Right hand shake
extern const RAW_ACTION action_023; // Eat
extern const RAW_ACTION action_024; // Push ups 1
extern const RAW_ACTION action_025; // Sit rocking 1
extern const RAW_ACTION action_026; // Tail wag, butt
extern const RAW_ACTION action_027; // Happy
extern const RAW_ACTION action_028; // Sitting, flea scratch 2
extern const RAW_ACTION action_029; // Sit, butt rub side to side
extern const RAW_ACTION action_030; // Sit guard
extern const RAW_ACTION action_031; // Sit yawn
extern const RAW_ACTION action_032; // Sit beg
extern const RAW_ACTION action_033; // Sit, shake right hand
extern const RAW_ACTION action_034; // Sit, hurt right paw
extern const RAW_ACTION action_035; // Sit, worry
extern const RAW_ACTION action_036; // Sit, hey over here
extern const RAW_ACTION action_037; // Sit rocking 2
extern const RAW_ACTION action_038; // Sitting hunger
extern const RAW_ACTION action_039; // Charge me, before battery change
extern const RAW_ACTION action_040; // Charge me, after battery change
extern const RAW_ACTION action_041; // Swim
extern const RAW_ACTION action_042; // Belly sections stretch
extern const RAW_ACTION action_043; // Sitting, wave hello
extern const RAW_ACTION action_044; // Belly, flea scratch
extern const RAW_ACTION action_045; // Belly, lying still
extern const RAW_ACTION action_046; // Belly, full body stretch
extern const RAW_ACTION action_047; // Belly sleep
extern const RAW_ACTION action_048; // Lying right side, rub belly
extern const RAW_ACTION action_049; // Lying right side,sick puppy
extern const RAW_ACTION action_050; // Nervous forward walk
extern const RAW_ACTION action_051; // Forward walk
extern const RAW_ACTION action_052; // Forward walking, dancing, play ful-attack
extern const RAW_ACTION action_053; // Head stand 1
extern const RAW_ACTION action_054; // Playful attack
extern const RAW_ACTION action_055; // Happy dancing
extern const RAW_ACTION action_056; // Lick
extern const RAW_ACTION action_057; // Attention short pre
extern const RAW_ACTION action_058; // Attention short post
extern const RAW_ACTION action_059; // Sit give hug
extern const RAW_ACTION action_060; // Sit give paw bent
extern const RAW_ACTION action_061; // Sit give paw, give hug arms
extern const RAW_ACTION action_062; // Looking around up
extern const RAW_ACTION action_063; // Looking around down
extern const RAW_ACTION action_064; // Shaking head to say 'no' 1
extern const RAW_ACTION action_065; // Nod to say 'yes' 1
extern const RAW_ACTION action_066; // Nod to say 'yes' 2
extern const RAW_ACTION action_067; // Nod to say 'yes' 3
extern const RAW_ACTION action_068; // Nod to say 'yes' 4
extern const RAW_ACTION action_069; // Standing howl
extern const RAW_ACTION action_070; // Belly turn on axis left
extern const RAW_ACTION action_071; // Belly turn on axis right
extern const RAW_ACTION action_072; // Sitting turn on axis left
extern const RAW_ACTION action_073; // Sitting turn on axis right
extern const RAW_ACTION action_074; // Sitting butt walk forward
extern const RAW_ACTION action_075; // Sitting butt walk left
extern const RAW_ACTION action_076; // Sitting butt walk right
extern const RAW_ACTION action_077; // Slow forward walk
extern const RAW_ACTION action_078; // Fast forward walk 1
extern const RAW_ACTION action_079; // Fast forward walk 2
extern const RAW_ACTION action_080; // Central axis turn left
extern const RAW_ACTION action_081; // Central axis turn right
extern const RAW_ACTION action_082; // Fast reverse walk
extern const RAW_ACTION action_083; // Forward, then turn left 1
extern const RAW_ACTION action_084; // Forward, then turn left 2
extern const RAW_ACTION action_085; // Look around, turn left
extern const RAW_ACTION action_086; // Forward, then turn right 1
extern const RAW_ACTION action_087; // Look around, turn right
extern const RAW_ACTION action_088; // Forward, then turn left 3
extern const RAW_ACTION action_089; // Forward, then turn right 2
extern const RAW_ACTION action_090; // Get up from butt 1
extern const RAW_ACTION action_091; // Get up from butt 2
extern const RAW_ACTION action_092; // Head stand to belly stretch
extern const RAW_ACTION action_093; // Head stand 2
extern const RAW_ACTION action_094; // Side left to belly, left scratch
extern const RAW_ACTION action_095; // Side right to belly, right scratch
extern const RAW_ACTION action_096; // Right side to standing
extern const RAW_ACTION action_097; // Left side to standing
extern const RAW_ACTION action_098; // Sit and get up
extern const RAW_ACTION action_099; // To side, to belly
extern const RAW_ACTION action_100; // Sit up
extern const RAW_ACTION action_101; // Play dead on left side
extern const RAW_ACTION action_102; // Play dead on right side
extern const RAW_ACTION action_103; // Play dead side & bow
extern const RAW_ACTION action_104; // Fast robo walk forward
extern const RAW_ACTION action_105; // Fast robo turn left
extern const RAW_ACTION action_106; // Fast robo turn right
extern const RAW_ACTION action_107; // Fast robo walk, stand, walk
extern const RAW_ACTION action_108; // Fast robo turn right, left, ...
extern const RAW_ACTION action_109; // Takes a bow 1
extern const RAW_ACTION action_110; // Happy tail wag & bark
extern const RAW_ACTION action_111; // Cybie meets chirpychi
extern const RAW_ACTION action_112; // Cybie meets poochi
extern const RAW_ACTION action_113; // Cybie meets superpoochi
extern const RAW_ACTION action_114; // Cybie meets dinochi
extern const RAW_ACTION action_115; // Cybie meets meowchi
extern const RAW_ACTION action_116; // Cybie meets chis
extern const RAW_ACTION action_117; // Pet my head
extern const RAW_ACTION action_118; // New get up from seated
extern const RAW_ACTION action_119; // Get up from head
extern const RAW_ACTION action_120; // Cybie meets raptor
extern const RAW_ACTION action_121; // Side sleep left, twitch
extern const RAW_ACTION action_122; // Shaking head to say 'no' short
extern const RAW_ACTION action_123; // Nod to say 'yes' 5
extern const RAW_ACTION action_124; // Nod to say 'yes' 6
extern const RAW_ACTION action_125; // Shaking head to say 'no' 2
extern const RAW_ACTION action_126; // Nod
extern const RAW_ACTION action_127; // Belly sleep with sound
extern const RAW_ACTION action_128; // Pee left 1 with sound
extern const RAW_ACTION action_129; // Pee right 1 with sound
extern const RAW_ACTION action_130; // Sick puppy, side right with sound
extern const RAW_ACTION action_131; // Standing howl with sound
extern const RAW_ACTION action_132; // Shaking head to say 'no' with sound
extern const RAW_ACTION action_133; // Shaking head to say 'no' short with sound
extern const RAW_ACTION action_134; // Sniffing air with sound
extern const RAW_ACTION action_135; // Sniffing ground with sound 1
extern const RAW_ACTION action_136; // Nod to say 'yes' 3 with sound
extern const RAW_ACTION action_137; // Nod to say 'yes' 4 with sound
extern const RAW_ACTION action_138; // Nod to say 'yes' 5 with sound
extern const RAW_ACTION action_139; // Nod to say 'yes' 6 with sound
extern const RAW_ACTION action_140; // Stretch yawn with sound
extern const RAW_ACTION action_141; // Pee left 2 with sound
extern const RAW_ACTION action_142; // Pee right 2 with sound
extern const RAW_ACTION action_143; // Happy hang out sound
extern const RAW_ACTION action_144; // Happy tail wag and bark sound
extern const RAW_ACTION action_145; // Hyper hang out sound
extern const RAW_ACTION action_146; // Nod to say 'yes' 1 with sound
extern const RAW_ACTION action_147; // Nod to say 'yes' 2 with sound
extern const RAW_ACTION action_148; // Sleepy hang out sound
extern const RAW_ACTION action_149; // Sniffing ground with sound 2
extern const RAW_ACTION action_150; // Sad hang out sound
extern const RAW_ACTION action_151; // Sit yawn with sound 1
extern const RAW_ACTION action_152; // Sit yawn with sound 2
extern const RAW_ACTION action_153; // Eat with sound 1
extern const RAW_ACTION action_154; // Eat with sound 2
extern const RAW_ACTION action_155; // Sniffing ground with sound 3
extern const RAW_ACTION action_156; // Side sleep left, twitch with sound
extern const RAW_ACTION action_157; // Walk left
extern const RAW_ACTION action_158; // Walk front
extern const RAW_ACTION action_159; // Walk right
extern const RAW_ACTION action_160; // Move head left only
extern const RAW_ACTION action_161; // Move head middle only
extern const RAW_ACTION action_162; // Move head right only
extern const RAW_ACTION action_163; // Head Home
extern const RAW_ACTION action_164; // Mood hyper act
extern const RAW_ACTION action_165; // Mood happy act 1
extern const RAW_ACTION action_166; // Mood happy act 2
extern const RAW_ACTION action_167; // Mood sick act
extern const RAW_ACTION action_168; // Mood sad act
extern const RAW_ACTION action_169; // Mood sleepy act
extern const RAW_ACTION action_170; // Mood guard act
extern const RAW_ACTION action_171; // Head Move to say Yes
extern const RAW_ACTION action_172; // Head Move to say No
extern const RAW_ACTION action_173; // Short Pee Right
extern const RAW_ACTION action_174; // Nod head and head stand
extern const RAW_ACTION action_175; // Nod head and sit 1
extern const RAW_ACTION action_176; // Dance
extern const RAW_ACTION action_177; // Give paw
extern const RAW_ACTION action_178; // Pee left 3
extern const RAW_ACTION action_179; // Pee right 3
extern const RAW_ACTION action_180; // Neck down & up 1
extern const RAW_ACTION action_181; // Nod to say 'yes' 7
extern const RAW_ACTION action_182; // Nod head and sit 2
extern const RAW_ACTION action_183; // Nod and standing neutral
extern const RAW_ACTION action_184; // Nod and forward
extern const RAW_ACTION action_185; // Nod and guard
extern const RAW_ACTION action_186; // Nod and tail wag
extern const RAW_ACTION action_187; // Nod and push up
extern const RAW_ACTION action_188; // Neck down & up 2
extern const RAW_ACTION action_189; // Head shake
extern const RAW_ACTION action_190; // Sit 2
extern const RAW_ACTION action_191; // Standing neutral 2
extern const RAW_ACTION action_192; // Fast forward walk 3
extern const RAW_ACTION action_193; // Guard 3
extern const RAW_ACTION action_194; // Tail wag 2
extern const RAW_ACTION action_195; // Push ups 2
extern const RAW_ACTION action_196; // Attention End
extern const RAW_ACTION action_197; // Demo 1 (Life of i-Cybie)
extern const RAW_ACTION action_198; // Demo 2 (i-Cybie the GREAT)
extern const RAW_ACTION action_199; // Demo 3 Move
extern const RAW_ACTION action_200; // Standby
extern const RAW_ACTION action_202; // Self auto calibration - left side
extern const RAW_ACTION action_203; // Self auto calibration - right side
extern const RAW_ACTION action_204; // Self auto calibration - start
extern const RAW_ACTION action_205; // Communicate with poochi
extern const RAW_ACTION action_206; // Communicate with meowchi
extern const RAW_ACTION action_207; // Communicate with chis
extern const RAW_ACTION action_208; // Communicate with chirpychi
extern const RAW_ACTION action_209; // Communicate with superpoochi
extern const RAW_ACTION actionold_176; // actionold_176
extern const RAW_ACTION actionold_178; // actionold_178 - more peeing/bark
extern const RAW_ACTION actionold_181; // actionold_181
extern const RAW_ACTION actionold_202; // actionold_202 - same as 'Takes a bow 1'
extern const RAW_ACTION actionold_206; // actionold_206 - Sleep1
extern const RAW_ACTION actionold_207; // actionold_207 - Wakeup/Yawn
extern const RAW_ACTION actionold_208; // actionold_208 - Sleep2
extern const RAW_ACTION actionold_209; // actionold_209 - Wakeup/No Yawn
extern const RAW_ACTION actionold_210; // actionold_210 - end talking1
extern const RAW_ACTION actionold_211; // actionold_211 - end talking2
extern const RAW_ACTION actionold_212; // actionold_212 - nose detect1
extern const RAW_ACTION actionold_213; // actionold_213 - nose detect2
extern const RAW_ACTION actionold_214; // actionold_214 - nap, get up funny
extern const RAW_ACTION actionnew_01; // actionnew_01
extern const RAW_ACTION actionnew_02; // actionnew_02
extern const RAW_ACTION actionnew_03; // actionnew_03
extern const RAW_ACTION actionnew_04; // actionnew_04
extern const RAW_ACTION actionnew_05; // actionnew_05
extern const RAW_ACTION actionnew_06; // actionnew_06
extern const RAW_ACTION actionnew_07; // actionnew_07
extern const RAW_ACTION actionnew_08; // actionnew_08
extern const RAW_ACTION actionnew_09; // actionnew_09
extern const RAW_ACTION actionnew_10; // actionnew_10
extern const RAW_ACTION actionnew_11; // actionnew_11
extern const RAW_ACTION actionnew_12; // actionnew_12
extern const RAW_ACTION actionnew_13; // actionnew_13
extern const RAW_ACTION actionnew_14; // actionnew_14
extern const RAW_ACTION actionnew_15; // actionnew_15
extern const RAW_ACTION actionnew_16; // actionnew_16
extern const RAW_ACTION actionnew_17; // actionnew_17
extern const RAW_ACTION actionnew_18; // actionnew_18
extern const RAW_ACTION actionnew_19; // actionnew_19
extern const RAW_ACTION actionnew_20; // actionnew_20
extern const RAW_ACTION actionnew_21; // actionnew_21
extern const RAW_ACTION actionnew_22; // actionnew_22
extern const RAW_ACTION actionnew_23; // actionnew_23
extern const RAW_ACTION actionnew_24; // actionnew_24
extern const RAW_ACTION actionnew_25; // actionnew_25
extern const RAW_ACTION actionnew_26; // actionnew_26
extern const RAW_ACTION actionnew_27; // actionnew_27
extern const RAW_ACTION actionnew_28; // actionnew_28
extern const RAW_ACTION actionnew_29; // actionnew_29
extern const RAW_ACTION actionnew_30; // actionnew_30
extern const RAW_ACTION actionnew_31; // actionnew_31
extern const RAW_ACTION actionnew_32; // actionnew_32
extern const RAW_ACTION actionnew_33; // actionnew_33
