// ICSDK2 - action2a.c - most actions - source for data
// (this file is automatically generated, do not edit

#include "icpriv.h"

const RAW_ACTION action_001 = // Tail wag 1
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 133, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_002 = // Crouch
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  69, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  70, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  71, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_003 = // Sniffing ground1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 128, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 129, 1, 0x03, POSTURE_STAND),
  }
};

const RAW_ACTION action_004 = // Guard 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 160, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 161, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_005 = // Dig it
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 157, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 158, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 159, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_006 = // Sniffing air
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  38, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  39, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_007 = // Sitting, flea scratch 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 178, 1, 0x00, POSTURE_LIE),
	ACTION_PART( 179, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_008 = // Pee right 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  21, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  22, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  23, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_009 = // Pee right 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  48, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  49, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  50, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_010 = // Pee left 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  18, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  19, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  20, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_011 = // Pee left 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  45, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  46, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  47, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_012 = // Sniffing ground 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART(  40, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_013 = // Sniffing ground 3
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 181, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 182, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_014 = // Guard 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 162, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 161, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_015 = // Sniffing and raising hand
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 175, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 176, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_016 = // Sit 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  51, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  52, 1, 0x00, POSTURE_SIT),
	ACTION_PART(  53, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_017 = // Play
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 170, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_018 = // Standing neutral 1
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_019 = // Stretch yawn
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART(  43, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  44, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_020 = // Rocking 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 166, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_021 = // Rocking 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 165, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_022 = // Right hand shake
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 132, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_023 = // Eat
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 169, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_024 = // Push ups 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 171, 1, 0x00, POSTURE_LIE),
	ACTION_PART( 172, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_025 = // Sit rocking 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 173, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_026 = // Tail wag, butt
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 183, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_027 = // Happy
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 163, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_028 = // Sitting, flea scratch 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 180, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_029 = // Sit, butt rub side to side
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 141, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_030 = // Sit guard
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 147, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 197, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_031 = // Sit yawn
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 156, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_032 = // Sit beg
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 140, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_033 = // Sit, shake right hand
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 151, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_034 = // Sit, hurt right paw
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 149, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 150, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_035 = // Sit, worry
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 152, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_036 = // Sit, hey over here
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 148, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_037 = // Sit rocking 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 177, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_038 = // Sitting hunger
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  30, 1, 0x00, POSTURE_SIT),
	ACTION_PART(  31, 1, 0x00, POSTURE_SIT),
	ACTION_PART(  32, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_039 = // Charge me, before battery change
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 136, 1, 0x00, POSTURE_SIT),
  }
};

const RAW_ACTION action_040 = // Charge me, after battery change
{
  1, /*COUNT*/
  2, /*REPEAT*/
  {
	ACTION_PART( 135, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_041 = // Swim
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 137, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 138, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 139, 1, 0x00, POSTURE_LIE),
  }
};

const RAW_ACTION action_042 = // Belly sections stretch
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  10, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  11, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  12, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_043 = // Sitting, wave hello
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  33, 1, 0x00, POSTURE_SIT),
	ACTION_PART(  34, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_044 = // Belly, flea scratch
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(   1, 1, 0x00, POSTURE_STAND),
	ACTION_PART(   2, 1, 0x00, POSTURE_STAND),
	ACTION_PART(   3, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_045 = // Belly, lying still
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(   7, 1, 0x00, POSTURE_STAND),
	ACTION_PART(   8, 1, 0x00, POSTURE_STAND),
	ACTION_PART(   9, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_046 = // Belly, full body stretch
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(   4, 1, 0x00, POSTURE_STAND),
	ACTION_PART(   5, 1, 0x00, POSTURE_STAND),
	ACTION_PART(   6, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_047 = // Belly sleep
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  13, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  14, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  15, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_048 = // Lying right side, rub belly
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  24, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  25, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  26, 1, 0x00, POSTURE_RECOVER2),
  }
};

const RAW_ACTION action_049 = // Lying right side,sick puppy
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  27, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  28, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  29, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_050 = // Nervous forward walk
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 101, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 102, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 103, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION action_051 = // Forward walk
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 153, 1, 0x53, POSTURE_STAND),
	ACTION_PART( 154, 1, 0x53, POSTURE_STAND),
	ACTION_PART( 155, 1, 0x53, POSTURE_STAND),
  }
};

const RAW_ACTION action_052 = // Forward walking, dancing, play ful-attack
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 184, 1, 0x53, POSTURE_STAND),
	ACTION_PART( 185, 1, 0x53, POSTURE_STAND),
	ACTION_PART( 186, 1, 0x53, POSTURE_STAND),
  }
};

const RAW_ACTION action_053 = // Head stand 1
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  97, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_054 = // Playful attack
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 108, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 109, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_055 = // Happy dancing
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 164, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_056 = // Lick
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 174, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_057 = // Attention short pre
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 168, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_058 = // Attention short post
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 167, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_059 = // Sit give hug
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 142, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 143, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_060 = // Sit give paw bent
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 144, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_061 = // Sit give paw, give hug arms
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 145, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 146, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_062 = // Looking around up
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  17, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_063 = // Looking around down
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  16, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_064 = // Shaking head to say 'no' 1
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  37, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_065 = // Nod to say 'yes' 1
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 105, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_066 = // Nod to say 'yes' 2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 106, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_067 = // Nod to say 'yes' 3
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  41, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_068 = // Nod to say 'yes' 4
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  42, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_069 = // Standing howl
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  35, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_070 = // Belly turn on axis left
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  63, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  64, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  65, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_071 = // Belly turn on axis right
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  66, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  67, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  68, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_072 = // Sitting turn on axis left
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 123, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_073 = // Sitting turn on axis right
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 124, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_074 = // Sitting butt walk forward
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  89, 1, 0x00, POSTURE_SIT),
	ACTION_PART(  90, 1, 0x00, POSTURE_SIT),
	ACTION_PART(  91, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_075 = // Sitting butt walk left
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 118, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 119, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 120, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_076 = // Sitting butt walk right
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 121, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 122, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_077 = // Slow forward walk
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 126, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 127, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION action_078 = // Fast forward walk 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  78, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_079 = // Fast forward walk 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  81, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_080 = // Central axis turn left
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  60, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_081 = // Central axis turn right
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  61, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_082 = // Fast reverse walk
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  79, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(  80, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_083 = // Forward, then turn left 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  62, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_084 = // Forward, then turn left 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  56, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_085 = // Look around, turn left
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  58, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_086 = // Forward, then turn right 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  57, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_087 = // Look around, turn right
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  59, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_088 = // Forward, then turn left 3
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  54, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_089 = // Forward, then turn right 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  55, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_090 = // Get up from butt 1
{
  1, /*COUNT*/
  2, /*REPEAT*/
  {
	ACTION_PART(  93, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_091 = // Get up from butt 2
{
  1, /*COUNT*/
  2, /*REPEAT*/
  {
	ACTION_PART(  94, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_092 = // Head stand to belly stretch
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  96, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_093 = // Head stand 2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  98, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_094 = // Side left to belly, left scratch
{
  1, /*COUNT*/
  5, /*REPEAT*/
  {
	ACTION_PART( 112, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_095 = // Side right to belly, right scratch
{
  1, /*COUNT*/
  6, /*REPEAT*/
  {
	ACTION_PART( 113, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_096 = // Right side to standing
{
  1, /*COUNT*/
  6, /*REPEAT*/
  {
	ACTION_PART( 115, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_097 = // Left side to standing
{
  1, /*COUNT*/
  5, /*REPEAT*/
  {
	ACTION_PART( 114, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_098 = // Sit and get up
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 117, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_099 = // To side, to belly
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  92, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_100 = // Sit up
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 125, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_101 = // Play dead on left side
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 110, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_102 = // Play dead on right side
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 111, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_103 = // Play dead side & bow
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 100, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_104 = // Fast robo walk forward
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  87, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_105 = // Fast robo turn left
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  85, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_106 = // Fast robo turn right
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  86, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_107 = // Fast robo walk, stand, walk
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  88, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_108 = // Fast robo turn right, left, ...
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  82, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  83, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(  84, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_109 = // Takes a bow 1
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  77, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_110 = // Happy tail wag & bark
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  95, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_111 = // Cybie meets chirpychi
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART(  72, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_112 = // Cybie meets poochi
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  75, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_113 = // Cybie meets superpoochi
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  76, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_114 = // Cybie meets dinochi
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  73, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_115 = // Cybie meets meowchi
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART(  74, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_116 = // Cybie meets chis
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  99, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_117 = // Pet my head
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 107, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_118 = // New get up from seated
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_119 = // Get up from head
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 187, 1, 0x00, POSTURE_HEAD),
  }
};

const RAW_ACTION action_120 = // Cybie meets raptor
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 188, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_121 = // Side sleep left, twitch
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 189, 1, 0x00, POSTURE_RECOVER1),
	ACTION_PART( 190, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 191, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_122 = // Shaking head to say 'no' short
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 192, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_123 = // Nod to say 'yes' 5
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 193, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_124 = // Nod to say 'yes' 6
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 194, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_125 = // Shaking head to say 'no' 2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 195, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_126 = // Nod
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 196, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_127 = // Belly sleep with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  13, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 198, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 199, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_128 = // Pee left 1 with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  18, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 200, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 229, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_129 = // Pee right 1 with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  21, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 201, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 230, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_130 = // Sick puppy, side right with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  27, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 202, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  29, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_131 = // Standing howl with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 203, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_132 = // Shaking head to say 'no' with sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 204, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_133 = // Shaking head to say 'no' short with sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 205, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_134 = // Sniffing air with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  38, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 206, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_135 = // Sniffing ground with sound 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 207, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_136 = // Nod to say 'yes' 3 with sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 208, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_137 = // Nod to say 'yes' 4 with sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 209, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_138 = // Nod to say 'yes' 5 with sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 210, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_139 = // Nod to say 'yes' 6 with sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 211, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_140 = // Stretch yawn with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 212, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  44, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_141 = // Pee left 2 with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  45, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 213, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  47, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_142 = // Pee right 2 with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  48, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 214, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  50, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_143 = // Happy hang out sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 215, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_144 = // Happy tail wag and bark sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 216, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_145 = // Hyper hang out sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 217, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_146 = // Nod to say 'yes' 1 with sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 218, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_147 = // Nod to say 'yes' 2 with sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 219, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_148 = // Sleepy hang out sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 220, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_149 = // Sniffing ground with sound 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 221, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 129, 1, 0x03, POSTURE_STAND),
  }
};

const RAW_ACTION action_150 = // Sad hang out sound
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 222, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_151 = // Sit yawn with sound 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 223, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_152 = // Sit yawn with sound 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 224, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_153 = // Eat with sound 1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 225, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_154 = // Eat with sound 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 226, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_155 = // Sniffing ground with sound 3
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 181, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 227, 1, 0x03, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_156 = // Side sleep left, twitch with sound
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 189, 1, 0x00, POSTURE_RECOVER1),
	ACTION_PART( 228, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 191, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_157 = // Walk left
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1094, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1008, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION action_158 = // Walk front
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1095, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1010, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION action_159 = // Walk right
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1096, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1009, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION action_160 = // Move head left only
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1094, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  36, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_161 = // Move head middle only
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1095, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  36, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_162 = // Move head right only
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1096, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  36, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_163 = // Head Home
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1011, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_164 = // Mood hyper act
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1014, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_165 = // Mood happy act 1
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1012, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_166 = // Mood happy act 2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1073, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_167 = // Mood sick act
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1071, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_168 = // Mood sad act
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1013, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_169 = // Mood sleepy act
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1069, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_170 = // Mood guard act
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1070, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_171 = // Head Move to say Yes
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_172 = // Head Move to say No
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1016, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_173 = // Short Pee Right
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1072, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_174 = // Nod head and head stand
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x00, POSTURE_STAND),
	ACTION_PART(1082, 1, 0x00, POSTURE_HEAD),
  }
};

const RAW_ACTION action_175 = // Nod head and sit 1
{
  4, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 117, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 181, 2, 0x00, POSTURE_SIT),
	ACTION_PART( 104, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_176 = // Dance
{
  4, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 185, 1, 0x53, POSTURE_STAND),
	ACTION_PART( 186, 1, 0x53, POSTURE_STAND),
	ACTION_PART( 187, 1, 0x53, POSTURE_STAND),
  }
};

const RAW_ACTION action_177 = // Give paw
{
  4, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 117, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 146, 1, 0x00, POSTURE_SIT),
	ACTION_PART( 147, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_178 = // Pee left 3
{
  4, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  18, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  19, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  20, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_179 = // Pee right 3
{
  4, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  21, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  22, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  23, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_180 = // Neck down & up 1
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x00, POSTURE_STAND),
	ACTION_PART(1101, 1, 0x20, POSTURE_STAND),
  }
};

const RAW_ACTION action_181 = // Nod to say 'yes' 7
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 107, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_182 = // Nod head and sit 2
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 117, 1, 0x40, POSTURE_SIT),
  }
};

const RAW_ACTION action_183 = // Nod and standing neutral
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  36, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_184 = // Nod and forward
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x40, POSTURE_STAND),
	ACTION_PART(1104, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_185 = // Nod and guard
{
  4, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 161, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 162, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_186 = // Nod and tail wag
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 134, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_187 = // Nod and push up
{
  4, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1015, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  36, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 172, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 173, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_188 = // Neck down & up 2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1101, 1, 0x20, POSTURE_STAND),
  }
};

const RAW_ACTION action_189 = // Head shake
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1103, 1, 0x20, POSTURE_STAND),
  }
};

const RAW_ACTION action_190 = // Sit 2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 116, 1, 0x40, POSTURE_SIT),
  }
};

const RAW_ACTION action_191 = // Standing neutral 2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_192 = // Fast forward walk 3
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1104, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_193 = // Guard 3
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 131, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 161, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 162, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_194 = // Tail wag 2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_195 = // Push ups 2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  36, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 172, 1, 0x40, POSTURE_STAND),
	ACTION_PART( 173, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_196 = // Attention End
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 167, 1, 0x40, POSTURE_STAND),
  }
};

// action_197 is in separate source file

// action_198 is in separate source file

const RAW_ACTION action_199 = // Demo 3 Move
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 134, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(  78, 1, 0x5f, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION action_200 = // Standby
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 168, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION action_202 = // Self auto calibration - left side
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1080, 1, 0x40, POSTURE_RECOVER1),
	ACTION_PART(1077, 1, 0x40, POSTURE_RECOVER1),
  }
};

const RAW_ACTION action_203 = // Self auto calibration - right side
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1083, 1, 0x40, POSTURE_RECOVER2),
	ACTION_PART(1076, 1, 0x40, POSTURE_RECOVER2),
  }
};

const RAW_ACTION action_204 = // Self auto calibration - start
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 189, 1, 0x00, POSTURE_RECOVER1),
  }
};

const RAW_ACTION action_205 = // Communicate with poochi
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1133, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_206 = // Communicate with meowchi
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1134, 1, 0x00, POSTURE_SIT),
	ACTION_PART(  72, 1, 0x00, POSTURE_STAND),
	ACTION_PART(1138, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_207 = // Communicate with chis
{
  2, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1135, 1, 0x03, POSTURE_STAND),
	ACTION_PART(1139, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_208 = // Communicate with chirpychi
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1136, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION action_209 = // Communicate with superpoochi
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1137, 1, 0x00, POSTURE_STAND),
	ACTION_PART(1141, 1, 0x00, POSTURE_SIT),
	ACTION_PART(1140, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_176 = // actionold_176
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  18, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  19, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  20, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_178 = // actionold_178 - more peeing/bark
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  21, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  22, 1, 0x40, POSTURE_STAND),
	ACTION_PART(  23, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_181 = // actionold_181
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 107, 1, 0x40, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_202 = // actionold_202 - same as 'Takes a bow 1'
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  77, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_206 = // actionold_206 - Sleep1
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1105, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_207 = // actionold_207 - Wakeup/Yawn
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1106, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_208 = // actionold_208 - Sleep2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1107, 1, 0x00, POSTURE_RECOVER1),
  }
};

const RAW_ACTION actionold_209 = // actionold_209 - Wakeup/No Yawn
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1108, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_210 = // actionold_210 - end talking1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(  48, 1, 0x00, POSTURE_STAND),
	ACTION_PART(1129, 1, 0x00, POSTURE_STAND),
	ACTION_PART(  50, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_211 = // actionold_211 - end talking2
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1128, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_212 = // actionold_212 - nose detect1
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART(1130, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 161, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_213 = // actionold_213 - nose detect2
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART( 130, 1, 0x03, POSTURE_STAND),
	ACTION_PART(1131, 1, 0x00, POSTURE_STAND),
	ACTION_PART( 161, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionold_214 = // actionold_214 - nap, get up funny
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1132, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_01 = // actionnew_01
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1142, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_02 = // actionnew_02
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1151, 6, 0x40, POSTURE_STAND),
	ACTION_PART( 131, 1, 0x00, POSTURE_STAND),
	ACTION_PART(1142, 1, 0x00, POSTURE_STAND),
	ACTION_PART(1149, 8, 0x5c, POSTURE_STAND),
	ACTION_PART(1142, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_03 = // actionnew_03
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1143, 1, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_04 = // actionnew_04
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1144, 2, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_05 = // actionnew_05
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1145, 2, 0x00, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_06 = // actionnew_06
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1148, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1149, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_07 = // actionnew_07
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1148, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1149, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_08 = // actionnew_08
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1150, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_09 = // actionnew_09
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1150, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_10 = // actionnew_10
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1149, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_11 = // actionnew_11
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1149, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_12 = // actionnew_12
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1146, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1150, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_13 = // actionnew_13
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1146, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1150, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_14 = // actionnew_14
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1149, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_15 = // actionnew_15
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1150, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_16 = // actionnew_16
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1146, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_17 = // actionnew_17
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1148, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5c, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_18 = // actionnew_18
{
  7, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1147, 2, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1155, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1151, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_19 = // actionnew_19
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_20 = // actionnew_20
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1149, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1147, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_21 = // actionnew_21
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1150, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1147, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_22 = // actionnew_22
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1150, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_23 = // actionnew_23
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1149, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_24 = // actionnew_24
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1147, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_25 = // actionnew_25
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1154, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_26 = // actionnew_26
{
  7, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1148, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1149, 4, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_27 = // actionnew_27
{
  7, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1146, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1150, 4, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_28 = // actionnew_28
{
  7, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1148, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1149, 1, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_29 = // actionnew_29
{
  1, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1158, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_30 = // actionnew_30
{
  4, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1150, 2, 0x40, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1147, 2, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_31 = // actionnew_31
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1150, 4, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_32 = // actionnew_32
{
  5, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1149, 4, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1151, 3, 0x5f, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

const RAW_ACTION actionnew_33 = // actionnew_33
{
  3, /*COUNT*/
  1, /*REPEAT*/
  {
	ACTION_PART(1152, 1, 0x5f, POSTURE_STAND),
	ACTION_PART(1149, 4, 0x5c, POSTURE_STAND),
	ACTION_PART(1153, 1, 0x5f, POSTURE_STAND),
  }
};

